config/routes.rb
Winnr::Application.routes.draw do

  
  resources :draws
  require "api"
  mount Draw::API => "/"

end

app/models/draw.rb
class Draw < ActiveRecord::Base

	validates :competition_code, :code, :draw_type, :presence => true
	validates :code, :uniqueness => {:scope => :competition_code}
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery  
end

app/controllers/draws_controller.rb
class DrawsController < ApplicationController

	respond_to :json

  # GET /draws
  # GET /draws.json
  def index
    @draws = Draw.paginate(:page => params[:page], :per_page => 50)
    @winning_draws = Draw.where(:selection => "WINNER")
    @draw = Draw.new

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @draws }
    end
  end

  # GET /draws/1
  # GET /draws/1.json
  def show
    @draw = Draw.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @draw }
    end
  end

  # GET /draws/new
  # GET /draws/new.json
  def new
    @draw = Draw.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @draw }
    end
  end

  # GET /draws/1/edit
  def edit
    @draw = Draw.find(params[:id])
  end

  # POST /draws
  # POST /draws.json
  def create
    @draw = Draw.new(params[:draw])

    respond_to do |format|
      if @draw.save
        format.html { redirect_to @draw, notice: 'Draw was successfully created.' }
        format.json { render json: @draw, status: :created, location: @draw }
      else
        format.html { render action: "new" }
        format.json { render json: @draw.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /draws/1
  # PUT /draws/1.json
  def update
    @draw = Draw.find(params[:id])

    respond_to do |format|
      if @draw.update_attributes(params[:draw])
        format.html { redirect_to @draw, notice: 'Draw was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @draw.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /draws/1
  # DELETE /draws/1.json
  def destroy
    @draw = Draw.find(params[:id])
    @draw.destroy

    respond_to do |format|
      format.html { redirect_to draws_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/draws_helper.rb
module DrawsHelper
end

app/views/draws/_form.html.erb
<%= form_for(@draw) do |f| %>
  <% if @draw.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@draw.errors.count, "error") %> prohibited this draw from being saved:</h2>

      <ul>
      <% @draw.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :competition_code %><br />
    <%= f.text_field :competition_code %>
  </div>
  <div class="field">
    <%= f.label :code %><br />
    <%= f.text_field :code %>
  </div>
  <div class="field">
    <%= f.label :parameters %><br />
    <%= f.text_field :parameters %>
  </div>
  <div class="field">
    <%= f.label :draw_type %><br />
    <%= f.text_field :draw_type %>
  </div>
  <div class="field">
    <%= f.label :selection %><br />
    <%= f.text_area :selection %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/draws/edit.html.erb
<h1>Editing draw</h1>

<%= render 'form' %>

<%= link_to 'Show', @draw %> |
<%= link_to 'Back', draws_path %>

app/views/draws/index.html.erb
<h1>Draws Mockup</h1>
<table>
<tr>
<td style='vertical-align:top'>
<h2>Instant Win</h2>
<input id="instant_win" name="commit" type="submit" value="Instant Win">
</td>
<td>
<h2>Set Selection</h2>

<%= form_for(@draw) do |f| %>
  <% if @draw.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@draw.errors.count, "error") %> prohibited this draw from being saved:</h2>

      <ul>
      <% @draw.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :competition_code %><br />
    <%= f.text_field :competition_code %>
  </div>
  <div class="field">
    <%= f.label :code %><br />
    <%= f.text_field :code %>
  </div>
  <div class="field">
    <%= f.label :parameters %><br />
    <%= f.text_field :parameters %>
  </div>
  <%= f.hidden_field :draw_type, :value => 'group' %>
  <div class="actions">
    <%= f.submit 'Selection Draw', :class => 'button' %>
  </div>
<% end %>
</td>
</tr>
</table>

<h2>Winners</h2>

<table>
  <tr>
    <th>Comp</th>
    <th>Draw</th>
    <th>Draw type</th>
    <th>Start date</th>
    <th>End date</th>
    <th>Selection</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @winning_draws.each do |draw| %>
  <tr>
    <td><%= draw.competition_code %></td>
    <td><%= draw.code %></td>
    <td><%= draw.draw_type %></td>
    <td><%= draw.start_date%></td>
    <td><%= draw.end_date %></td>
    <td><%= draw.selection %></td>
    <td><%= link_to 'Show', draw %></td>
    <td><%= link_to 'Edit', edit_draw_path(draw) %></td>
    <td><%= link_to 'Destroy', draw, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>


<h2>All Draws</h2>
  <div class="pagination">
    <div class="page_info" style="float: right">
      <%= page_entries_info @draws, {:entry_name => 'Draw', :html => false} %>
    </div>
    <%= will_paginate @draws, :container => false %>
  </div>
<table>
  <tr>
    <th>Comp</th>
    <th>Draw</th>
    <th>Draw type</th>
    <th>Start date</th>
    <th>End date</th>
    <th>Selection</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @draws.each do |draw| %>
  <tr>
    <td><%= draw.competition_code %></td>
    <td><%= draw.code %></td>
    <td><%= draw.draw_type %></td>
    <td><%= draw.start_date%></td>
    <td><%= draw.end_date %></td>
    <td><%= draw.selection %></td>
    <td><%= link_to 'Show', draw %></td>
    <td><%= link_to 'Edit', edit_draw_path(draw) %></td>
    <td><%= link_to 'Destroy', draw, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />
<script>

  $(function() {
    $("#instant_win").click(function() {
      $.ajax({
				url: "http://localhost:3000/api/v1/draw",
				dataType: "json",
				type: "POST",
				processData: false,
				contentType: "application/json",
				accepts: "application/json",
				data: "{\"draw\":{\"code\":\"draw<%=rand(1000)%>\",\"competition_code\":\"comp1\",\"draw_type\":\"instant\",\"start_date\":\"<%=Time.now.beginning_of_day()%>\",\"end_date\":\"<%=Time.now.beginning_of_day() + 7.days%>\"}}",
				success: function( data ) {
					if (console && console.log){
						console.log( 'Sample of data:', data );
					}
				}
			});
    });
  });
  
</script>

app/views/draws/new.html.erb
<h1>New draw</h1>

<%= render 'form' %>

<%= link_to 'Back', draws_path %>

app/views/draws/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Competition code:</b>
  <%= @draw.competition_code %>
</p>

<p>
  <b>Code:</b>
  <%= @draw.code %>
</p>

<p>
  <b>Parameters:</b>
  <%= @draw.parameters %>
</p>

<p>
  <b>Draw type:</b>
  <%= @draw.draw_type %>
</p>

<p>
  <b>Selection:</b>
  <%= @draw.selection %>
</p>


<%= link_to 'Edit', edit_draw_path(@draw) %> |
<%= link_to 'Back', draws_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Winnr</title>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>